# Generated by Django 3.2.8 on 2021-12-04 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twitter_name', models.CharField(max_length=50)),
                ('last_login', models.DateTimeField(auto_now=True, null=True)),
                ('twitter_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Hashtags',
            fields=[
                ('word', models.CharField(max_length=100, null=True)),
                ('code', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tweets',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('tweet', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('hashtag', models.ManyToManyField(blank=True, related_name='hashtag', to='tweets.Hashtags')),
                ('like', models.ManyToManyField(blank=True, related_name='like', to=settings.AUTH_USER_MODEL)),
                ('twitter_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.account')),
                ('twitter_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True, null=True)),
                ('main_tweet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.tweets')),
                ('twitter_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tweets.account')),
                ('twitter_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
