# Generated by Django 3.2.8 on 2021-12-04 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='twitter_account',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='twitter_user',
            new_name='user',
        ),
    ]
